### ISSUE TITLE
Files Upload

### ISSUE THREAD

**Issue by Mhmdhammoud** [Mhmdhammoud/pms-back#18]
# Task files

## Manager 

- [x] Manager task file upload
- [x] Validate Manager before upload
- [x] Validate Manager Auth middleware
- [ ] Merge with Project Manager files

## Employee
- [x] Employee task file upload
- [x] Validate Employee Auth Middleware
- [x] Employee task file upload
- [ ] Merge with Project employee files

_All Files Are uploaded directly to Amazon S3_
[Files source](https://muallemy-storage.s3.eu-central-1.amazonaws.com/PMS)
